= Urban Vegetation Modeling Tool

== Overview

This project focuses on the development of a tool for incorporating vegetation into 3D urban models. Leveraging data from sources such as OpenStreetMap and Mapbox, our goal is to create a realistic representation of trees within the model. Trees significantly impact air and ground temperatures, as well as building energy consumption through shade and wind protection.

== Features

* Integration of vegetation data into 3D urban models
* Realistic representation of trees, including shape, size, location, and density
* Consideration of vegetation's impact on air and ground temperatures, as well as building energy consumption
* Efficient and scalable method suitable for large urban areas

== Getting Started

== Usage
=== Current usage : Basic use of the CGAL alpha wrapper

==== Compilation :
```bash
cd build
cmake --preset <release|debug> ..
make
```
==== Execution :
```bash
cd build
./run <input_file> <alpha> <offset>
```
The outpult mesh will be saved in  `/build`.

==== Example :
```bash
cd build
./run ../data/trees/oranger.off 500
```

==== Notes :
You can visualize the output mesh with **Meshlab** or any other mesh viewer. (note for myself : dont use meshlab on wayland...)


== Contributors

* https://github.com/GiulioCrp[GiulioCrp]
* https://github.com/PA-Senger[PA-Senger]