= ExaMA - Vegetation

== Overview

The goal of this project is to develop a tool that integrates vegetation (trees) into 3D urban models in order to improve the efficiency of thermal simulations.

== Installation and Usage

=== Install Required Packages

This project uses link:https://www.cgal.org[CGAL], link:https://curl.se/[curl].

If you don't want to install dependencies globally on your local machine you can use Miniforge or venv to create a new environment with the required packages:

=== Set up an environment 
We provide here two example of environment, Mamba and venv

==== Mamba environment:

```bash
# Download Miniforge
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh

# Install Miniforge
bash miniforge.sh -b -p $HOME/miniforge3 

# Activate Miniforge
source $HOME/miniforge3/bin/activate 

# Create a new Mamba environment
mamba create --name vegetation python=3.10 -y

# Activate the new environment
mamba activate vegetation
```

==== Or venv environment:
```bash
python3 -m venv .venv
source .venv/bin/activate
```

=== Install Required Packages

With the environment set up, install the required packages:
```bash

mamba install -c conda-forge cgal-cpp  fmt spdlog mpfr boost-cpp curl -y
```

=== Alternatively you can use a Docker container:
```bash
docker build -t 2024m1vegetation:latest .
docker run -it 2024m1vegetation:latest
```

Note: on VsCode you can use the Remote - Containers extension to reopen the project in a container.

=== Build the Project

Configure and build the project using CMake:
```bash
mkdir build
cd build

# Build the project
cmake ..

# Compile the project
make

# Run the tests
make test
```

=== Usage 

Use the configuration file `config.json` to specify:  

- the bounding box `bbox` of the area of interest ("bottom latitude, bottom longitude, top latitude, top longitude")

- the level of detail `LOD` (1, 2, or 3)

- the default height of the trees `default_height` (in meters) when the height is not available in the OpenStreetMap data

- the default genus of the trees `default_genus` when the genus is not available in the OpenStreetMap data

- the base name of the output file `output_file` saved in the `/output` directory


Then run the program:
```bash
cd build
./run
```

The output mesh will be saved in the `/output` directory (which is automatically 
created if needed).

You can visualize the output mesh with **Meshlab** or any other mesh viewer. (Note: Meshlab does not work well with Wayland.)


== Contributors

* https://github.com/GiulioCrp[GiulioCrp]
* https://github.com/PA-Senger[PA-Senger]