= Urban Vegetation Modeling Tool

== Overview

The goal of this project is to develop a tool that integrates vegetation data into 3D urban models. The tool will allow users to generate realistic representations of trees in urban environments, including their shape, size, location, and density. 

This is made in order to run simulations on the impact of vegetation on air and ground temperatures, as well as building energy consumption. 

More specifically sun masking and fluid dynamics simulations will be run to determine the impact of vegetation on the urban environment using tools such as Feel++.

== Installation and Usage

=== Environment Setup
This project configuration uses https://conan.io/[Conan] (version 1.63) for its dependancies.

Here we install Conan in a https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html[Mamba] environment via https://pypi.org/project/pip/[pip] :

```bash
# Download Miniforge
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh

# Install Miniforge
bash miniforge.sh -b -p $HOME/miniforge3 

# Activate Miniforge
source $HOME/miniforge3/bin/activate 

# Create a new Mamba environment
mamba create --name vegetation python=3.10 -y

# Activate the new environment
mamba activate vegetation
```

=== Install Required Packages

With the environment set up, install the required packages:

```bash
pip install -r requirements.txt
```

=== Build the Project

Configure and build the project using CMake:
```bash
# Configure CMake
cmake --preset default

# Build the project
cmake --build --preset default

# Test the build
ctest --preset default
```

=== Usage (currently a basic alpha wrapper)

To use the alpha wrapper, run the following command:

```bash
./build/default/bin/wrap <input_file> <alpha> <offset>
```

The output mesh will be saved in the `/output`` folder.

=== Example

Here's an example of how to use the alpha wrapper:

```bash
./build/default/bin/wrap data/trees/oranger.off 10
```

=== Notes

You can visualize the output mesh with **Meshlab** or any other mesh viewer. (Note: Meshlab does not work well with Wayland.)


== Contributors

* https://github.com/GiulioCrp[GiulioCrp]
* https://github.com/PA-Senger[PA-Senger]