= ExaMA - Vegetation

== Overview

The goal of this project is to develop a tool that integrates trees into 3D urban models in order to improve the efficiency of thermal and energy simulations.

== Installation and Usage

=== Required Packages

The following packages are needed to build the project:

- https://cmake.org/[CMake] (>= 3.15)
- https://curl.se/[libcurl]
- https://www.cgal.org/[CGAL] (master)
- https://git-scm.com/[Git]
- https://www.boost.org/[Boost]
- https://fmt.dev/[fmt]
- https://www.mpfr.org/[MPFR]

=== Installating package on Ubuntu

```bash
sudo apt-get update
sudo apt-get install -y build-essential cmake git libmpfr-dev libboost-dev libcurl4-openssl-dev libfmt-dev
```

=== Install CGAL
For our project, we need the master branch of CGAL.
```bash
git clone --branch master https://github.com/CGAL/cgal.git
cd cgal
mkdir cgal.build
cd cgal.build
cmake -DCMAKE_INSTALL_PREFIX=path_to/cgal.install ..
make install
```

=== Alternatively you can use the Docker container provided in the repository:
This container can be used for developpement, when building the image the project is copied in the container without building the project.


You might want to remove the `build` directory before running (and closing) the container to avoid conflicts.
```bash
docker build -t 2024m1vegetation:latest .
docker run -it 2024m1vegetation:latest
```

On VsCode you can use the Remote - Containers extension to reopen the project in a container.

=== Build the Project
Configure and build the project using CMake:
```bash
mkdir build
cd build
# path used for the Docker container
cmake -DCMAKE_PREFIX_PATH=/workspace/cgal/cgal.install ..
make

# Run the tests
ctest
```

=== Usage

Use the configuration file `config.json` to specify:

- the bounding box `bbox` of the area of interest ("bottom latitude, bottom longitude, top latitude, top longitude")

- the `origin` used in the conversion from latitude and longitude to Cartesian coordinates

- the level of detail `LOD` (0, 1, 2, 3) of the meshes

- the `altitude` of the ground 

- the default height of the trees `default_height_range` (in meters) when the height is not available in the OpenStreetMap data

- the default genus of the trees `default_genus` when the genus is not available in the OpenStreetMap data

- the `input_building_mesh` file for making the union of the building with the trees

- if we merge the trees with the buildings or not with `merge_builtings_trees`

- the base name of the output file `output_file` saved in the `/output` directory

Use the `genus.json` file to specify the genus and height of the trees to be used in the simulation.

- `known_genus` is a list of genus for which we have a base mesh
- `cedrus_like` is a list of the genus for which the cedrus mesh model will be used
- etc.

If you wish you can mesh your own tree model using link:https://doc.cgal.org/latest/Alpha_wrap_3/index.html[CGAL Alpha Wrapper] by running:

```bash
./build/wrap Genus.stl <alpha> <offset>
```

and move the result to the `tree_ref` directory. Then add the genus to the `known_genus` in the `trees.json` file.

Finnaly run the program:
```bash
./build/src/run
```

The output mesh and some metrics will be saved in the `/output` directory (which is automatically created if needed).

You can visualize the output mesh with **Meshlab**, **Paraview** or any other mesh viewer. (Note: Meshlab does not work well with Wayland.)


== Contributors

* https://github.com/GiulioCrp[GiulioCrp]
* https://github.com/PA-Senger[PA-Senger]
