= ExaMA - Vegetation

== Overview

The goal of this project is to develop a tool that integrates vegetation (trees) into 3D urban models in order to improve the efficiency of thermal simulations.

This reposirory contains:

- include: Header files
- src: Source files
- test: Test files

== Installation and Usage

=== Install Required Packages

This project uses link:https://www.cgal.org[CGAL], link:https://curl.se/[curl] and link:https://github.com/nlohmann/json[nlohmann/json libraries]. Go check them out if you don't have them locally installed.

If you don't want to install them globally on your local machine you can use Miniforge to create a new environment with the required packages:

==== Mamba environment:

```bash
# Download Miniforge
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh

# Install Miniforge
bash miniforge.sh -b -p $HOME/miniforge3 

# Activate Miniforge
source $HOME/miniforge3/bin/activate 

# Create a new Mamba environment
mamba create --name vegetation python=3.10 -y

# Activate the new environment
mamba activate vegetation
```

==== Or venv environment:
```bash
python3 -m venv .venv
source .venv/bin/activate
```

=== Install Required Packages

With the environment set up, install the required packages:

```bash
pip install -r requirements.txt
```

=== Build the Project

Configure and build the project using CMake:
```bash
# Configure CMake
cmake --preset default

# Build the project
cmake --build --preset default

# Test the build
ctest --preset default
```

=== Usage (currently a basic alpha wrapper)

To use the alpha wrapper, run the following command:

```bash
./build/default/bin/wrap <input_file> <alpha> <offset>
```

The output mesh will be saved in the `/output`` folder.

=== Example

Here's an example of how to use the alpha wrapper:

```bash
./build/default/bin/wrap data/trees/oranger.off 10
```

=== Notes

You can visualize the output mesh with **Meshlab** or any other mesh viewer. (Note: Meshlab does not work well with Wayland.)


== Contributors

* https://github.com/GiulioCrp[GiulioCrp]
* https://github.com/PA-Senger[PA-Senger]